### ISSUE TITLE
Cannot debug and see nrf logs 

### ISSUE THREAD

**Issue by kautham** [electronut/ElectronutLabs-hackaBLE#1]
I used all the tutorials that were provided in the readme and successfully ran the example projects. I am also using bumpy successfully. but however i cannot see the logs in the GDB console. For the ble projects we have to merge the softdevice and the projects hex files and then load the merged hex into hackable where both hex files do not have any debug symbols. 

I use SEGGER embedded studios for building the code.Then use the generated hex files for merging and loading it into hackable.  I use SDK 15. the only debug-able build i have is in the projects armgcc/_build folder project.out file which is generated after executing the "make" command. But it cannot be used as the .out file cannot be merged with the project.hex file. Even for the non ble projects the out file doesn't logs the nrf log messages. 

Is there any way to see the log messages and debug at the run time after merging with softdevice.hex file

**Comment by electronut** [comment]
This is not really an issue specific to hackaBLE.

Logging in nRF can use either Segger RTT or UART, which can be setup using the config file - please see Nordic documentation on it. Segger RTT is not possible if you are using bumpy, so you have to use UART.
